### ISSUE TITLE
aspnet-request-post-body  content 

### ISSUE THREAD

**Issue by HinaSheikh** [HinaSheikh/ClientBooking#1]
hey everyone 
I am using {aspnet-request-post-body} attribute in nlog.config to log request body. I want to make annotation in c# like jsonignore so that Nlog attribute {aspnet-request-post-body} does not include those properties in log file?
any solution for that I search a lot but could not find the best one that meets my requirements

**Comment by snakefoot** [comment]
Think you will get better reponse if you create the issue for the NLog-project. And fill out the [question-template](https://github.com/NLog/NLog/issues/new/choose).

**Comment by HinaSheikh** [comment]
well thanks I ll do it
